---
title: "Weekly-Assignment-1"
author: "Chris Fink"
date: "2023-01-12"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---
# Git must be downloaded to the computer before proceeding with these steps  

1. To download git, I found it necessary to download Xcode to my Mac. This can be done by going to the apple website listed below and downloading Xcode along with the tool set that will be used by homebrew.
2. Once this is done, homebrew will then be used to install git to the computer by using the command listen on the website in the terminal of the computer.
3. After the installation is completed, you will then run another command in the terminal that will finsih adapting git to the computer.

## How to Set Up a Github Page in RStudio  

1. In order to set up a Github page in RStudio, you will first need to create a new repository in your Guthub account.
2. Once this is done, it is important to then copy the https link that Github produces for later use in RStudio.
3. In the top right of Rstudio, there is button that reads new project and this is where you must go next.
4. The next step is to select version control and then git after that.
5. A new screen will pop up which will allow for you to insert the link that was copied from Github and, most importantly, you must name the project the same name as you did for the repository on Github.
6. Once this is done, the computer and Github are now linked on that project.
7. Now it is possible to start creating the webpage.
8. First up is opening a new RMarkdown file and when saving it, naming it "index".
9. Next up is making the actual changes to this page through RMarkdown and once that is complete, make sure to knit the page to html.
Once it is ready to be sent to Github, then you must open up the terminal in RStudio.
10. Go through the adding and committing steps to set up the push of the information to the Github.

## Troubleshooting and helpful links

It is important to look to make sure that each of the commands are put into the terminal rather than in the console or elsewhere. If not then there may be confusion that follows.  

If the installation of git has failed more then once, I would suggest redownloading xcode as it can help to reset the process. It did for me after I had failed repeatedly on the download.  

When downloading git, if you did not use the apple website for downloading xcod and the developer tools needed for git, it will fail to download so using the wbesite below is imperative for the effective downloading of git.

[apple website for downloading xcode](https://developer.apple.com)

